// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {title: 'Bulid your own Supaglue', version: '0.0.0'},
  servers: [{url: 'http://localhost:3000/api'}],
} as const
export default oasMeta
