// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {title: 'OpenInt OpenAPI', version: '0.0.0'},
  servers: [{url: 'https://tonyx.ngrok.dev/api/v0'}],
} as const
export default oasMeta
